<?php 
namespace Flex\Components\Columns;

use Flex\Components\EntryArrayTrait;

enum ColumnsEnum : string
{
    use EntryArrayTrait;

    case ID                    = 'id';
    case NAME                  = 'name';
    case USERID                = 'userid';
    case PASSWD                = 'passwd';
    case RE_PASSWD             = 're_passwd';
    case EMAIL                 = 'email';
    case BIRTHDAY              = 'birthday';
    case START_DATE            = 'start_date';
    case END_DATE              = 'end_date';
    case LINKURL               = 'linkurl';
    case VIEW_COUNT            = 'view_count';
    case TITLE                 = 'title';
    case EXTRACT_ID            = 'extract_id';
    case EXTRACT_DATA          = 'extract_data';
    case DESCRIPTION           = 'description';
    case SIGNDATE              = 'signdate';
    case SIGNTIME              = 'signtime';
    case SIGNTIMESTAMP         = 'signtimestamp';
    case POINT                 = 'point';
    case RECOMMAND             = 'recommand';
    case IS_PUSH               = 'is_push';
    case LEVEL                 = 'level';
    case CELLPHONE             = 'cellphone';
    case MUID                  = 'muid';
    case TOTAL                 = 'total';
    case CARTID                = 'cartid';
    case DVMAC                 = 'dvmac';
    case UP_DATE               = 'up_date';
    case RECENTLY_CONNECT_DATE = 'recently_connect_date';
    case LOGOUT_TIME           = 'logout_time';
    case ALARM_READDATE        = 'alarm_readdate';
    case INTRODUCE             = 'introduce';
    case AUTHEMAILKEY          = 'authemailkey';
    case HEADLINE              = 'headline';
    case CATEGORY              = 'category';
    case IP                    = 'ip';
    case USAGE_INT             = 'usage_int';
    case ACCESS_TOKEN          = 'access_token';
    case TOKEN                 = 'token';
    case SECRET_KEY            = 'secret_key';
    case MODULE_ID             = 'module_id';
    case ITEM_ID               = 'item_id';
    case ITEMS                 = 'items';
    case GID                   = 'gid';
    case LIST_PRICE            = "list_price";
    case PRICE                 = "price";
    case SALE_PRICE            = "sale_price";
    case SOLD_OUT              = "sold_out";
    case OPTION1               = "option1";
    case OPTION2               = "option2";
    case ORIGIN                = "origin";
    case DELIVERY_FEE          = "delivery_fee";
    case IS_AFTER_DELIVERY     = "is_after_delivery";
    case INDIVIDUAL_DELIVERY   = "individual_delivery";
    case HASHTAGS              = "hashtags";
    case FID                   = "fid";
    case WID                   = "wid";
    case MESSAGE               = "message";
    case IS_PRINT              = 'is_print';
    case REPLY_COUNT           = "reply_count";
    case ITEM_COUNT            = 'item_count';
    case Q                     = 'q';
    case PAGE                  = 'page';
    case NEWPASSWD             = 'newpasswd';
    case RE_NEWPASSWD          = 're_newpasswd';
    case SALE_STATE            = 'sale_state';
    case REGIDATE              = 'regidate';
    case NUMBER                = 'number';
    case SP                    = 'sp';
    case PUBLICATIONS_NUMBER   = 'publications_number';
    case OWNERS_NUMBER         = 'owners_number';
    case USES_NUMBER           = 'uses_number';
    case SP_UNIT   = 'sp_unit';
    case ORDERCODE = "ordercode";
    case PAYMETHOD = "paymethod";
    case PAYMENT   = "payment";
    case TERM      = "term";
    case MEMO      = "memo";
    case ORDERER   = "orderer";
    case SHIPPING  = "shipping";
    case SALEPOINT = "salepoint";
    case PROOF     = "proof";
}
?>